apiVersion: v1
kind: Pod
metadata:
  name: argocd-nginx-pod-akshay
  labels:
    app.kubernetes.io/name: argocd-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80

      # test1




